amazon:
  defaultRegion: us-east-2
  dynamodb:
    endpoint: http://localhost:8000

featureToggle:
  useLocalEndpoint: false

info:
  app:
    name: bluetechlab-order
    description: teste info fabio